language: ruby
script: "bundle exec rspec spec"
env:
  global:
    - CI=true
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
gemfile:
  - Gemfile
  - Gemfile-pure
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby
cache: bundler
sudo: false
matrix:
  allow_failures:
    - rvm: jruby
dist: trusty
