language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 2.2.5
  - 2.3.1
  - jruby
  - rbx
gemfile:
  - Gemfile
  - Gemfile-pure
env:
  global:
    - CI=true
cache: bundler
sudo: false
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
