language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - rbx-2
gemfile:
  - Gemfile
  - Gemfile-pure
env:
  global:
    - CI=true
cache: bundler
sudo: false
matrix:
  allow_failures:
      - rvm: jruby
      - rvm: rbx-2
