# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rdf-rdfxml}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gregg Kellogg"]
  s.date = %q{2010-06-03}
  s.description = %q{    RDF::RDFXML is an RDF/XML reader and writer for Ruby using the RDF.rb library suite.
}
  s.email = %q{gregg@kellogg-assoc.com}
  s.extra_rdoc_files = [
    "AUTHORS",
     "History.txt",
     "README.rdoc"
  ]
  s.files = [
    ".yardopts",
     "AUTHORS",
     "History.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "example.rb",
     "lib/rdf/rdfxml.rb",
     "lib/rdf/rdfxml/format.rb",
     "lib/rdf/rdfxml/reader.rb",
     "lib/rdf/rdfxml/version.rb",
     "lib/rdf/rdfxml/writer.rb"
  ]
  s.homepage = %q{http://github.com/gkellogg/rdf-rdfxml}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{RDF/XML reader/writer for RDF.rb.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rdf>, [">= 0.1.6"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.3.3"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rdf-spec>, [">= 0"])
      s.add_development_dependency(%q<activesupport>, [">= 2.3.0"])
    else
      s.add_dependency(%q<rdf>, [">= 0.1.6"])
      s.add_dependency(%q<nokogiri>, [">= 1.3.3"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdf-spec>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 2.3.0"])
    end
  else
    s.add_dependency(%q<rdf>, [">= 0.1.6"])
    s.add_dependency(%q<nokogiri>, [">= 1.3.3"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdf-spec>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 2.3.0"])
  end
end

