# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rdf-rdfxml}
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gregg Kellogg"]
  s.date = %q{2011-02-13}
  s.description = %q{RDF::RDFXML is an RDF/XML reader and writer for Ruby using the RDF.rb library suite.}
  s.email = %q{gregg@kellogg-assoc.com}
  s.extra_rdoc_files = [
    "AUTHORS",
    "CONTRIBUTORS",
    "History.rdoc",
    "README.md"
  ]
  s.files = [
    ".yardopts",
    "AUTHORS",
    "CONTRIBUTORS",
    "History.rdoc",
    "README.md",
    "Rakefile",
    "UNLICENSE",
    "VERSION",
    "etc/doap.nt",
    "etc/doap.xml",
    "example.rb",
    "lib/rdf/rdfxml.rb",
    "lib/rdf/rdfxml/format.rb",
    "lib/rdf/rdfxml/patches/array_hacks.rb",
    "lib/rdf/rdfxml/patches/graph_properties.rb",
    "lib/rdf/rdfxml/patches/literal_hacks.rb",
    "lib/rdf/rdfxml/patches/nokogiri_hacks.rb",
    "lib/rdf/rdfxml/reader.rb",
    "lib/rdf/rdfxml/version.rb",
    "lib/rdf/rdfxml/vocab.rb",
    "lib/rdf/rdfxml/writer.rb",
    "rdf-rdfxml.gemspec",
    "script/console",
    "script/parse",
    "script/tc",
    "script/yard-to-rubyforge",
    "spec/.gitignore",
    "spec/format_spec.rb",
    "spec/graph_spec.rb",
    "spec/literal_spec.rb",
    "spec/matchers.rb",
    "spec/rdf_test.rb",
    "spec/reader_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/writer_spec.rb"
  ]
  s.homepage = %q{http://github.com/gkellogg/rdf-rdfxml}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{RDF/XML reader/writer for RDF.rb.}
  s.test_files = [
    "spec/format_spec.rb",
    "spec/graph_spec.rb",
    "spec/literal_spec.rb",
    "spec/matchers.rb",
    "spec/rdf_test.rb",
    "spec/reader_spec.rb",
    "spec/spec_helper.rb",
    "spec/writer_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rdf>, [">= 0.3.1"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_development_dependency(%q<open-uri-cached>, [">= 0"])
      s.add_development_dependency(%q<spira>, [">= 0.0.12"])
      s.add_development_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_development_dependency(%q<rdf-spec>, [">= 0.3.1"])
      s.add_development_dependency(%q<rdf-isomorphic>, [">= 0.3.4"])
      s.add_development_dependency(%q<yard>, [">= 0.6.4"])
    else
      s.add_dependency(%q<rdf>, [">= 0.3.1"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_dependency(%q<open-uri-cached>, [">= 0"])
      s.add_dependency(%q<spira>, [">= 0.0.12"])
      s.add_dependency(%q<rspec>, [">= 2.5.0"])
      s.add_dependency(%q<rdf-spec>, [">= 0.3.1"])
      s.add_dependency(%q<rdf-isomorphic>, [">= 0.3.4"])
      s.add_dependency(%q<yard>, [">= 0.6.4"])
    end
  else
    s.add_dependency(%q<rdf>, [">= 0.3.1"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
    s.add_dependency(%q<open-uri-cached>, [">= 0"])
    s.add_dependency(%q<spira>, [">= 0.0.12"])
    s.add_dependency(%q<rspec>, [">= 2.5.0"])
    s.add_dependency(%q<rdf-spec>, [">= 0.3.1"])
    s.add_dependency(%q<rdf-isomorphic>, [">= 0.3.4"])
    s.add_dependency(%q<yard>, [">= 0.6.4"])
  end
end

