#!/usr/bin/env ruby
# File: script/console
irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'

libs =  " -r irb/completion"
RDF = File.dirname(__FILE__) + "/../../rdf/lib"
libs << " -I #{RDF}" if File.directory?(RDF)
libs <<  " -r #{File.dirname(__FILE__) + '/../lib/rdf/rdfxml.rb'}"
puts "Loading rdf-rdfxml gem"
exec "#{irb} #{libs} --simple-prompt"
