#!/usr/bin/env ruby -s
require 'rubygems'
$:.unshift(File.expand_path(File.join(File.dirname(__FILE__), "..", 'lib')))
require 'rdf/rdfxml'
require 'spec/rdf_helper'
require 'getoptlong'

def run_tc(tc)
  puts "run #{tc.name}"
  puts tc.input if $verbose
  puts RDF::Writer.for($format.to_sym).buffer { |writer|
    RDF::RDFXML::Reader.new(tc.input, :base_uri => tc.about, :validate => $validate).each do |statement|
      writer << statement
    end
  }
end

$verbose = false
$format = :ntriples
$validate = false
suite = "rdfxml"
opts = GetoptLong.new(
  ["--debug", GetoptLong::NO_ARGUMENT],
  ["--verbose", GetoptLong::NO_ARGUMENT],
  ["--quiet", GetoptLong::NO_ARGUMENT],
  ["--suite", GetoptLong::OPTIONAL_ARGUMENT],
  ["--validate", GetoptLong::NO_ARGUMENT],
  ["--format", GetoptLong::REQUIRED_ARGUMENT]
)
opts.each do |opt, arg|
  case opt
  when '--verbose' then $verbose = true
  when '--quiet' then $quiet = true
  when '--debug' then ::RDF::RDFXML::debug = true
  when '--format' then $format = arg
  when '--suite' then suite = arg
  when '--validate' then $validate = true
  end
end

# Test URI and directory for different suites
TEST_PARAMS = {
  "rdfxml"  => [RDFCORE_TEST, RDFCORE_DIR],
}
test_cases = RdfHelper::TestCase.test_cases(*TEST_PARAMS[suite])

test_cases = test_cases.detect do |tc|
  next unless ARGV.empty? || ARGV.any? {|n| tc.name.match(/#{n}/)}
  run_tc(tc)
end
